// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330080932_Adding-bookings-table-with-configurations")]
    partial class Addingbookingstablewithconfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("Amenities", (string)null);
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckInDate");

                    b.HasIndex("CheckOutDate");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.HasIndex("VillaId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(10)")
                        .HasDefaultValue("USD");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods", (string)null);
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Statues", (string)null);
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas", (string)null);
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            SpecialDetails = "Villa 1 - Room 1",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            SpecialDetails = "Villa 1 - Room 2",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            SpecialDetails = "Villa 1 - Room 3",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            SpecialDetails = "Villa 2 - Room 1",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            SpecialDetails = "Villa 2 - Room 2",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            SpecialDetails = "Villa 2 - Room 3",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            SpecialDetails = "Villa 3 - Room 1",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            SpecialDetails = "Villa 3 - Room 2",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 303,
                            SpecialDetails = "Villa 3 - Room 3",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 401,
                            SpecialDetails = "Villa 4 - Room 1",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 402,
                            SpecialDetails = "Villa 4 - Room 2",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 403,
                            SpecialDetails = "Villa 4 - Room 3",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 501,
                            SpecialDetails = "Villa 5 - Room 1",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 502,
                            SpecialDetails = "Villa 5 - Room 2",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 503,
                            SpecialDetails = "Villa 5 - Room 3",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 601,
                            SpecialDetails = "Villa 6 - Room 1",
                            VillaId = 6
                        },
                        new
                        {
                            Villa_Number = 602,
                            SpecialDetails = "Villa 6 - Room 2",
                            VillaId = 6
                        },
                        new
                        {
                            Villa_Number = 603,
                            SpecialDetails = "Villa 6 - Room 3",
                            VillaId = 6
                        },
                        new
                        {
                            Villa_Number = 701,
                            SpecialDetails = "Villa 7 - Room 1",
                            VillaId = 7
                        },
                        new
                        {
                            Villa_Number = 702,
                            SpecialDetails = "Villa 7 - Room 2",
                            VillaId = 7
                        },
                        new
                        {
                            Villa_Number = 703,
                            SpecialDetails = "Villa 7 - Room 3",
                            VillaId = 7
                        },
                        new
                        {
                            Villa_Number = 801,
                            SpecialDetails = "Villa 8 - Room 1",
                            VillaId = 8
                        },
                        new
                        {
                            Villa_Number = 802,
                            SpecialDetails = "Villa 8 - Room 2",
                            VillaId = 8
                        },
                        new
                        {
                            Villa_Number = 803,
                            SpecialDetails = "Villa 8 - Room 3",
                            VillaId = 8
                        },
                        new
                        {
                            Villa_Number = 901,
                            SpecialDetails = "Villa 9 - Room 1",
                            VillaId = 9
                        },
                        new
                        {
                            Villa_Number = 902,
                            SpecialDetails = "Villa 9 - Room 2",
                            VillaId = 9
                        },
                        new
                        {
                            Villa_Number = 903,
                            SpecialDetails = "Villa 9 - Room 3",
                            VillaId = 9
                        },
                        new
                        {
                            Villa_Number = 1001,
                            SpecialDetails = "Villa 10 - Room 1",
                            VillaId = 10
                        },
                        new
                        {
                            Villa_Number = 1002,
                            SpecialDetails = "Villa 10 - Room 2",
                            VillaId = 10
                        },
                        new
                        {
                            Villa_Number = 1003,
                            SpecialDetails = "Villa 10 - Room 3",
                            VillaId = 10
                        },
                        new
                        {
                            Villa_Number = 1101,
                            SpecialDetails = "Villa 11 - Room 1",
                            VillaId = 11
                        },
                        new
                        {
                            Villa_Number = 1102,
                            SpecialDetails = "Villa 11 - Room 2",
                            VillaId = 11
                        },
                        new
                        {
                            Villa_Number = 1103,
                            SpecialDetails = "Villa 11 - Room 3",
                            VillaId = 11
                        },
                        new
                        {
                            Villa_Number = 1201,
                            SpecialDetails = "Villa 12 - Room 1",
                            VillaId = 12
                        },
                        new
                        {
                            Villa_Number = 1202,
                            SpecialDetails = "Villa 12 - Room 2",
                            VillaId = 12
                        },
                        new
                        {
                            Villa_Number = 1203,
                            SpecialDetails = "Villa 12 - Room 3",
                            VillaId = 12
                        },
                        new
                        {
                            Villa_Number = 1301,
                            SpecialDetails = "Villa 13 - Room 1",
                            VillaId = 13
                        },
                        new
                        {
                            Villa_Number = 1302,
                            SpecialDetails = "Villa 13 - Room 2",
                            VillaId = 13
                        },
                        new
                        {
                            Villa_Number = 1303,
                            SpecialDetails = "Villa 13 - Room 3",
                            VillaId = 13
                        },
                        new
                        {
                            Villa_Number = 1401,
                            SpecialDetails = "Villa 14 - Room 1",
                            VillaId = 14
                        },
                        new
                        {
                            Villa_Number = 1402,
                            SpecialDetails = "Villa 14 - Room 2",
                            VillaId = 14
                        },
                        new
                        {
                            Villa_Number = 1403,
                            SpecialDetails = "Villa 14 - Room 3",
                            VillaId = 14
                        },
                        new
                        {
                            Villa_Number = 1501,
                            SpecialDetails = "Villa 15 - Room 1",
                            VillaId = 15
                        },
                        new
                        {
                            Villa_Number = 1502,
                            SpecialDetails = "Villa 15 - Room 2",
                            VillaId = 15
                        },
                        new
                        {
                            Villa_Number = 1503,
                            SpecialDetails = "Villa 15 - Room 3",
                            VillaId = 15
                        },
                        new
                        {
                            Villa_Number = 1601,
                            SpecialDetails = "Villa 16 - Room 1",
                            VillaId = 16
                        },
                        new
                        {
                            Villa_Number = 1602,
                            SpecialDetails = "Villa 16 - Room 2",
                            VillaId = 16
                        },
                        new
                        {
                            Villa_Number = 1603,
                            SpecialDetails = "Villa 16 - Room 3",
                            VillaId = 16
                        },
                        new
                        {
                            Villa_Number = 1901,
                            SpecialDetails = "Villa 19 - Room 1",
                            VillaId = 19
                        },
                        new
                        {
                            Villa_Number = 1902,
                            SpecialDetails = "Villa 19 - Room 2",
                            VillaId = 19
                        },
                        new
                        {
                            Villa_Number = 1903,
                            SpecialDetails = "Villa 19 - Room 3",
                            VillaId = 19
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany("Amenities")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Book", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Status", "Status")
                        .WithMany("Books")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhiteLagoon.Domain.Entities.User", "User")
                        .WithMany("Books")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany("Books")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Payment", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhiteLagoon.Domain.Entities.Status", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhiteLagoon.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany("VillaNumbers")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Status", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.User", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Books");

                    b.Navigation("VillaNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
