// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321193444_nothingchanges")]
    partial class nothingchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas", (string)null);
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            SpecialDetails = "Villa 1 - Room 1",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            SpecialDetails = "Villa 1 - Room 2",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            SpecialDetails = "Villa 1 - Room 3",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            SpecialDetails = "Villa 2 - Room 1",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            SpecialDetails = "Villa 2 - Room 2",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            SpecialDetails = "Villa 2 - Room 3",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            SpecialDetails = "Villa 3 - Room 1",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            SpecialDetails = "Villa 3 - Room 2",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 303,
                            SpecialDetails = "Villa 3 - Room 3",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 401,
                            SpecialDetails = "Villa 4 - Room 1",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 402,
                            SpecialDetails = "Villa 4 - Room 2",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 403,
                            SpecialDetails = "Villa 4 - Room 3",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 501,
                            SpecialDetails = "Villa 5 - Room 1",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 502,
                            SpecialDetails = "Villa 5 - Room 2",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 503,
                            SpecialDetails = "Villa 5 - Room 3",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 601,
                            SpecialDetails = "Villa 6 - Room 1",
                            VillaId = 6
                        },
                        new
                        {
                            Villa_Number = 602,
                            SpecialDetails = "Villa 6 - Room 2",
                            VillaId = 6
                        },
                        new
                        {
                            Villa_Number = 603,
                            SpecialDetails = "Villa 6 - Room 3",
                            VillaId = 6
                        },
                        new
                        {
                            Villa_Number = 701,
                            SpecialDetails = "Villa 7 - Room 1",
                            VillaId = 7
                        },
                        new
                        {
                            Villa_Number = 702,
                            SpecialDetails = "Villa 7 - Room 2",
                            VillaId = 7
                        },
                        new
                        {
                            Villa_Number = 703,
                            SpecialDetails = "Villa 7 - Room 3",
                            VillaId = 7
                        },
                        new
                        {
                            Villa_Number = 801,
                            SpecialDetails = "Villa 8 - Room 1",
                            VillaId = 8
                        },
                        new
                        {
                            Villa_Number = 802,
                            SpecialDetails = "Villa 8 - Room 2",
                            VillaId = 8
                        },
                        new
                        {
                            Villa_Number = 803,
                            SpecialDetails = "Villa 8 - Room 3",
                            VillaId = 8
                        },
                        new
                        {
                            Villa_Number = 901,
                            SpecialDetails = "Villa 9 - Room 1",
                            VillaId = 9
                        },
                        new
                        {
                            Villa_Number = 902,
                            SpecialDetails = "Villa 9 - Room 2",
                            VillaId = 9
                        },
                        new
                        {
                            Villa_Number = 903,
                            SpecialDetails = "Villa 9 - Room 3",
                            VillaId = 9
                        },
                        new
                        {
                            Villa_Number = 1001,
                            SpecialDetails = "Villa 10 - Room 1",
                            VillaId = 10
                        },
                        new
                        {
                            Villa_Number = 1002,
                            SpecialDetails = "Villa 10 - Room 2",
                            VillaId = 10
                        },
                        new
                        {
                            Villa_Number = 1003,
                            SpecialDetails = "Villa 10 - Room 3",
                            VillaId = 10
                        },
                        new
                        {
                            Villa_Number = 1101,
                            SpecialDetails = "Villa 11 - Room 1",
                            VillaId = 11
                        },
                        new
                        {
                            Villa_Number = 1102,
                            SpecialDetails = "Villa 11 - Room 2",
                            VillaId = 11
                        },
                        new
                        {
                            Villa_Number = 1103,
                            SpecialDetails = "Villa 11 - Room 3",
                            VillaId = 11
                        },
                        new
                        {
                            Villa_Number = 1201,
                            SpecialDetails = "Villa 12 - Room 1",
                            VillaId = 12
                        },
                        new
                        {
                            Villa_Number = 1202,
                            SpecialDetails = "Villa 12 - Room 2",
                            VillaId = 12
                        },
                        new
                        {
                            Villa_Number = 1203,
                            SpecialDetails = "Villa 12 - Room 3",
                            VillaId = 12
                        },
                        new
                        {
                            Villa_Number = 1301,
                            SpecialDetails = "Villa 13 - Room 1",
                            VillaId = 13
                        },
                        new
                        {
                            Villa_Number = 1302,
                            SpecialDetails = "Villa 13 - Room 2",
                            VillaId = 13
                        },
                        new
                        {
                            Villa_Number = 1303,
                            SpecialDetails = "Villa 13 - Room 3",
                            VillaId = 13
                        },
                        new
                        {
                            Villa_Number = 1401,
                            SpecialDetails = "Villa 14 - Room 1",
                            VillaId = 14
                        },
                        new
                        {
                            Villa_Number = 1402,
                            SpecialDetails = "Villa 14 - Room 2",
                            VillaId = 14
                        },
                        new
                        {
                            Villa_Number = 1403,
                            SpecialDetails = "Villa 14 - Room 3",
                            VillaId = 14
                        },
                        new
                        {
                            Villa_Number = 1501,
                            SpecialDetails = "Villa 15 - Room 1",
                            VillaId = 15
                        },
                        new
                        {
                            Villa_Number = 1502,
                            SpecialDetails = "Villa 15 - Room 2",
                            VillaId = 15
                        },
                        new
                        {
                            Villa_Number = 1503,
                            SpecialDetails = "Villa 15 - Room 3",
                            VillaId = 15
                        },
                        new
                        {
                            Villa_Number = 1601,
                            SpecialDetails = "Villa 16 - Room 1",
                            VillaId = 16
                        },
                        new
                        {
                            Villa_Number = 1602,
                            SpecialDetails = "Villa 16 - Room 2",
                            VillaId = 16
                        },
                        new
                        {
                            Villa_Number = 1603,
                            SpecialDetails = "Villa 16 - Room 3",
                            VillaId = 16
                        },
                        new
                        {
                            Villa_Number = 1901,
                            SpecialDetails = "Villa 19 - Room 1",
                            VillaId = 19
                        },
                        new
                        {
                            Villa_Number = 1902,
                            SpecialDetails = "Villa 19 - Room 2",
                            VillaId = 19
                        },
                        new
                        {
                            Villa_Number = 1903,
                            SpecialDetails = "Villa 19 - Room 3",
                            VillaId = 19
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany("VillaNumbers")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Navigation("VillaNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
